### ISSUE TITLE
Panic upon running the demos

### ISSUE THREAD

**Issue by niclashoyer** [Gigoteur/PX8#16]
Just gave the current master branch a try on Fedora  25 using rust 1.16.0.

I get a panic in [src/sound/mod.rs](https://github.com/Gigoteur/PX8/blob/master/src/sound/mod.rs#L74)

```
$ ./target/release/px8 -s 4./demos/ski.py 
[2017-04-22][23:38:06][INFO] Frontend: SDL2 init
[2017-04-22][23:38:06][INFO] Frontend: SDL2 Video init
[2017-04-22][23:38:06][INFO] Frontend: SDL2 event pump
[2017-04-22][23:38:06][INFO] Frontend: creating renderer
[2017-04-22][23:38:06][INFO] [SDL] Creating window fullscreen=false opengl=true
[2017-04-22][23:38:06][INFO] [SDL] Creating renderer
[2017-04-22][23:38:06][INFO] [SDL] Creating texture
[2017-04-22][23:38:06][INFO] Frontend: SDL2 audio
thread '<unnamed>' panicked at 'index out of bounds: the len is 256 but the index is 256', src/sound/mod.rs:74
```

**Comment by popey** [comment]
Confirmed on Ubuntu 16.04 LTS.
```$ prime/bin/px8 parts/px8/src/demos/voxel/voxel.px8 
[2017-04-22][23:26:38][INFO] Frontend: SDL2 init
[2017-04-22][23:26:38][INFO] Frontend: SDL2 Video init
[2017-04-22][23:26:38][INFO] Frontend: SDL2 event pump
[2017-04-22][23:26:38][INFO] Frontend: creating renderer
[2017-04-22][23:26:38][INFO] [SDL] Creating window fullscreen=false opengl=true
[2017-04-22][23:26:38][INFO] [SDL] Creating renderer
[2017-04-22][23:26:38][INFO] [SDL] Creating texture
[2017-04-22][23:26:38][INFO] Frontend: SDL2 audio
[2017-04-22][23:26:38][INFO] Frontend: initialise controllers
[2017-04-22][23:26:38][INFO] Init Controllers
thread '<unnamed>' panicked at 'index out of bounds: the len is 256 but the index is 256', src/sound/mod.rs:74
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)```

**Comment by hallucino** [comment]
Hi,

I will disable the sound right now, it is clearly not stable or finish

**Comment by hallucino** [comment]
Could you try to recompile ?
cargo run --release --features "cpython lua" && ./target/release/px8 -s 4 ./games/ski/ski.px8

(I removed demos/ski.py it was the same code)

**Comment by niclashoyer** [comment]
works! great 😄
